name: Snyk Scan
on:
  push:
    branches:
      - main

jobs:
  snyk-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: snyk/actions/snyk-cli@stable
        with:
          token: ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk scan
        run: |
          snyk test
