name: Snyk Scan
on:
  push:
    branches:
      - main

jobs:
  snyk-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Install Snyk CLI
        uses: snyk/actions/snyk-cli@v2
        with:
          token: ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk scan
        uses: snyk/actions/snyk-scan@v2
        with:
          severity: high
          output-file: snyk-report.txt
